import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mela backend monitoring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mela Business
        </h1>
        <p className={styles.description}>Meilleur plateforme de distribution de la boisson</p>
        <Link href="/api/graphql">
          <button className={styles.button}>{"Acceder a l'API"}</button>
        </Link>

      </main>


    </div>
  )
}
